# Set Default Sleep Timer
SLEEP_TIMER: 0

# Set up UFrame and EDEX paths
INGESTION:
    command: /home/developer/uframes/ooi/bin/ingestsender
    # log_path: /home/wdk/race/log/
    log_path: .
EDEX:
    command: /home/developer/uframes/ooi/bin/edex-server
    log_path: /home/developer/uframes/ooi/uframe-1.0/edex/logs/

